
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `desc` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `posts` (`title`, `desc`) VALUES
('test', 'test-desc'),
('test-title-0', 'test-title-0'),
('test-title-1', 'test-title-1'),
('test-title-2', 'test-title-2'),
('test-title-3', 'test-title-3'),
('test-title-4', 'test-title-4'),
('test-title-5', 'test-title-5'),
('test-title-6', 'test-title-6'),
('test-title-7', 'test-title-7'),
('test-title-8', 'test-title-8'),
('test-title-9', 'test-title-9'),
('test-title-10', 'test-title-10'),
('test-title-11', 'test-title-11'),
('test-title-12', 'test-title-12'),
('test-title-13', 'test-title-13'),
('test-title-14', 'test-title-14'),
('test-title-15', 'test-title-15'),
('test-title-16', 'test-title-16'),
('test-title-17', 'test-title-17'),
('test-title-18', 'test-title-18'),
('test-title-19', 'test-title-19'),
('test-title-20', 'test-title-20'),
('test-title-21', 'test-title-21'),
('test-title-22', 'test-title-22'),
('test-title-23', 'test-title-23'),
('test-title-24', 'test-title-24'),
('test-title-25', 'test-title-25'),
('test-title-26', 'test-title-26'),
('test-title-27', 'test-title-27'),
('test-title-28', 'test-title-28'),
('test-title-29', 'test-title-29'),
('test-title-30', 'test-title-30'),
('test-title-31', 'test-title-31'),
('test-title-32', 'test-title-32'),
('test-title-33', 'test-title-33'),
('test-title-34', 'test-title-34'),
('test-title-35', 'test-title-35'),
('test-title-36', 'test-title-36'),
('test-title-37', 'test-title-37'),
('test-title-38', 'test-title-38'),
('test-title-39', 'test-title-39'),
('test-title-40', 'test-title-40'),
('test-title-41', 'test-title-41'),
('test-title-42', 'test-title-42'),
('test-title-43', 'test-title-43'),
('test-title-44', 'test-title-44'),
('test-title-45', 'test-title-45'),
('test-title-46', 'test-title-46'),
('test-title-47', 'test-title-47'),
('test-title-48', 'test-title-48'),
('test-title-49', 'test-title-49'),
('test-title-50', 'test-title-50');